# Rename this file to `docker-compose.yml` and then execute 'docker compose up -d' to run the docker container
version: '3.8' # Specify the Docker Compose file format version

services:
  agora-ai: # Define a service named 'agora-ai'
    image: skgadi/agora-ai-sbs:latest # Specify the Docker image to use
    container_name: temp-suresh-agora-ai # Optional: Assign a custom name to the container
    restart: unless-stopped # Ensure the container restarts automatically unless explicitly stopped

    # Define environment variables for the container
    environment:
      MY_PAI_GEMINI_API_KEY: "AaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaAaA" # Replace with your actual Gemini API key
      MY_PAI_ADMIN_PASSWORD: "1234" # Replace with your desired admin password
    # it will now be accessible on port 8080 of your host machine.
    ports:
      - "8080:3000" # Host port 8080 mapped to container port 3000
